-- Választási adatbázis létrehozása
CREATE DATABASE IF NOT EXISTS valasztas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE valasztas;

CREATE TABLE IF NOT EXISTS megye (
    MegyeId INT AUTO_INCREMENT PRIMARY KEY,
    Nev VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS part (
    PartId INT AUTO_INCREMENT PRIMARY KEY,
    Nev VARCHAR(200) NOT NULL,
    Rovidites VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS eredmeny (
    EredmenyId INT AUTO_INCREMENT PRIMARY KEY,
    Ev INT NOT NULL,
    MegyeId INT NOT NULL,
    PartId INT NOT NULL,
    Szavazatok INT NOT NULL DEFAULT 0,
    Mandatumok INT NOT NULL DEFAULT 0,
    UNIQUE KEY uq_eredmeny (Ev, MegyeId, PartId),
    FOREIGN KEY (MegyeId) REFERENCES megye(MegyeId),
    FOREIGN KEY (PartId) REFERENCES part(PartId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
